### ISSUE TITLE
In-App download from wherigofoundation

### ISSUE THREAD

**Issue by capoaira** [biylda/WhereYouGo#36] opened 2019-11-19 19:20 UTC
Hello, 
at the moment you can download cartridges from wherigo.com in the app. If you have wherigofundation cartridges, you have to move the file complicately to the correct folder. Many cachers have problems with that and unfortunately they can not play the wherigos.

**Comment by SchoolGuy** [comment] 2019-11-20 06:18
@capoaira If you look at the repository and at the owner, then you will see that the project is not moving forward for a long time now! We would need to create a fork of this project and then rewrite parts of Whereyougo for this feature request.

**Comment by SchoolGuy** [comment] 2019-11-20 06:20
If you look at the Wherigofoundation project on Github you will also see that this project is dead. (They have their own Player)

**Comment by SimonHeimberg** [comment] 2019-12-30 23:51
<s>Duplicate of #37</s>

**Comment by SimonHeimberg** [comment] 2019-12-30 23:53
> If you look at the Wherigofoundation project on Github you will also see that this project is dead. (They have their own Player)

Do you mean https://github.com/WFoundation/WF.Player.Android , with last commit 5 years ago?

**Comment by SchoolGuy** [comment] 2019-12-31 07:35
> > If you look at the Wherigofoundation project on Github you will also see that this project is dead. (They have their own Player)
> 
> Do you mean https://github.com/WFoundation/WF.Player.Android , with last commit 5 years ago?

Yes I mean that one.

**Comment by bekuno** [comment] 2019-12-31 08:34
> Duplicate of #37

No. This PR is for a FR to add Wherigofoundation, but the other is a bug when downloading from wherigo.com

**Comment by SimonHeimberg** [comment] 2020-01-02 11:14
> > Duplicate of #37
> 
> No. This PR is for a FR to add Wherigofoundation, but the other is a bug when downloading from wherigo.com

Right, sorry.

I did not see that this difference. And I did not know I can download cartridges from https://www.wherigofoundation.com/

**Comment by capoaira** [comment] 2020-01-02 15:41
> I did not see that this difference. And I did not know I can download cartridges from https://www.wherigofoundation.com/

Yes, but not like a cartridge from wherigo.com.
When I open a Wherigo.com cartridge link, I can open and download it from Wheryougo. If I open a cartridge link from the Wherigofoundation, I have to open and download the cartridge with the web browser and then move it to the WherYouGo folder. This is complicated to find when you do it for the first time. Or if you rarely play wherigos.
I am an owner of some wherigos and I am often asked how it works with wherigofoundation.

**Comment by SimonHeimberg** [comment] 2020-01-03 17:04
suggestion 1, allow to open/import downloaded file:
 * configure handler for "*.gwc" to src/main/AndroidManifest.xml
 * handle in `onCreate()` in src/main/java/menion/android/whereyougo/gui/activity/MainActivity.java
   * handler moves or copies the file to the expected folder
   * probably the handler allows to start the cartridge

I suggest to open/import the downloaded file because then we do not need to support downloads from more pages, it works with all. No update when something changes on the site. No providing of username and passwords.

This could also be a sepparate app, in case development does not continue here.

**Comment by capoaira** [comment] 2020-01-03 19:14
Thank you for that suggestion. But I have no idea how to do this. I also don't know how to create an .apk from the repo.

**Comment by Lineflyer** [comment] 2020-01-03 19:23
As mentioned in #37 I am trying to get in touch with the repo owner and am in contact with Menion as the original author to help in case the repo owner does not respond. 

I am sure we will find a wait to continue either in this repo or a new clone. I will update #37 if there are any news.

**Comment by SimonHeimberg** [comment] 2020-01-03 21:01
> If you look at the Wherigofoundation project on Github you will also see that this project is dead. (They have their own Player)

But if you look at https://www.wherigofoundation.com/ChangeLog/, you see the last change on 2019-05-12, so the foundation seems to do something.

**Closed as completed** 2020-06-27 09:47 UTC
